services:
  - type: web
    name: orcestra-dicom-app
    env: node
    plan: free
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 22.16.0
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_REDIRECT_URI
        value: https://orcestra-dicom-app.onrender.com/api/oauth/google/callback
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: DIRECTOR_CODE
        sync: false
      - key: OAUTH_SERVER_URL
        sync: false